---

- name: Install Avamar Agent
  hosts: all
  gather_facts: yes
  become: yes

  tasks:

    - name: create temporary directory to get app
      tempfile:
        state: directory
        suffix: avamar
      register: r_temp
      delegate_to: localhost
      run_once: yes
      become: no

    - name: Get agent
      get_url:
        url: https://fts.capgemini.com/pubpwd/19038359737396/AvamarClient-linux-sles11-x86_64-7.4.101-58.zip
        url_username: "{{ cap_username }}"
        url_password:  "{{ cap_password }}"
        dest: "{{ r_temp.path }}/avamar.zip"
      delegate_to: localhost
      run_once: yes
      become: no

    - name: Copy agent to targets
      copy:
        src: "{{ r_temp.path }}/avamar.zip"
        dest: /tmp/

    - name: Install needed packages
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - unzip

    - name: Unzip on target 
      unarchive:
        src: "/tmp/avamar.zip"
        dest: /tmp
        remote_src: yes
      become: yes 

    - name: Install Agent
      yum:
        name: /tmp/AvamarClient-linux-sles11-x86_64-7.4.101-58.rpm
        state: present

    - name: Start Avamar service, if not running
      service:
        name: avagent
        state: started





